# Generated by Django 4.2.1 on 2024-01-03 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artiste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(default='name@example.com', max_length=254)),
                ('website', models.URLField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_lieu', models.CharField(max_length=100)),
                ('rue', models.CharField(max_length=100)),
                ('num', models.IntegerField()),
                ('cp', models.IntegerField()),
                ('ville', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Spectacle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('description', models.CharField(max_length=1000)),
                ('genre', models.CharField(choices=[('Genre', 'Genre'), ('Cirque_art_et_forain_de_la_rue', 'Cirque Art Forain De La Rue'), ('Compte_poesie_et_litterature', 'Compte Poesie Et Litterature')], default='Genre', max_length=50)),
                ('public', models.CharField(choices=[('Public', 'Public'), ('Jeunes', 'Jeunes'), ('Adultes', 'Adultes')], default='Public', max_length=50)),
                ('animation', models.BooleanField(default=False)),
                ('duree', models.CharField(max_length=50, null=True)),
                ('artiste', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artiste.artiste')),
                ('lieu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artiste.lieu')),
            ],
        ),
    ]
