# Generated by Django 4.2.1 on 2024-01-03 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artiste', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectacle',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='date',
            name='spectacle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artiste.spectacle'),
        ),
    ]
